<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/fashion-calendar-home.css', 'FashionCalendarModule'));
?>
<div id="hero" class="col-12">
    <div class="row align-items-center">
        <div class="col-md-6">
            <img class="img-fluid" src="<?php echo $this->assetUrl('img/finley.png'); ?>"
                alt="Drawing of Ruth Finley on the telephone">
        </div>
        <div class="col-md-6">
            <div id="tag">70 Years of Fashion History</div>
            <p id="lead">
                From 1941 to 2014, Ruth Finley published the <em>Fashion Calendar</em>, an independent, weekly
                periodical
                that served as the official scheduling clearinghouse for the American fashion industry. Digitized by the
                Fashion Institute of Technology, the <em>Fashion Calendar</em> is now searchable,
                graphable and mappable.
            </p>
        </div>
    </div>
</div>
<div id="features" class="col-12">
    <div class="row row-cols-1 row-cols-md-3 gx-lg-5">
        <div class="col feature">
            <h2><span><i class="fas fa-book-open"></i>Browse Issues</span></h2>
            <p>
                Included are three periodicals published by Ruth Finley: Fashion Calendar (1941-2014), Home Furnishings
                Calendar (1947-1951), and Fashion International (1972-2008). For researchers, this method is the closest
                to handling the material directly. Each issue is directly searchable and can
                be freely downloaded as a PDF.
            </p>
            <div class="button-container d-flex">
                <a href="/page/issues" class="btn btn-fit-pink floating-action mx-auto" aria-label="Browse Issues">
                    <span class="action-container">
                        Issues
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true" title="Browse Issues">
                        </i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col feature">
            <h2><span><i class="fas fa-table"></i>Explore Data</span></h2>
            <p>
                Information about the events listed in the <em>Fashion Calendar</em>—the who, what, when, where—has been
                extracted and parsed from each issue. Names and entities in the listings (i.e. designers and brands)
                have been categorized to highlight gender, race, social class, sexual identity, nationality, etc. The
                data of nearly 200,000 events can be searched, map, and graphed, allowing users to discover rich
                patterns and threads in the history of fashion.
            </p>
            <div class="button-container d-flex">
                <a href="/page/data" class="btn btn-fit-blue floating-action mx-auto" aria-label="Explore Data">
                    <span class="action-container">
                        Data
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true" title="Explore Data">
                        </i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col feature">
            <h2><span><i class="fas fa-info-circle"></i>About</span></h2>
            <p>
                In 2020, FIT was awarded a "Hidden Collections" grant from the Council on Library and Information
                Resources to the digitize the Ruth Finley Collection, which is housed in the FIT Library's Special
                Collections
                and College Archives. The project culminated in this site, the Fashion Calendar Research Database, a
                joint initiative of the <a href="https://www.fitnyc.edu/academics/library/">Gladys
                    Marcus Library</a> and the <a
                    href="https://www.fitnyc.edu/academics/academic-divisions/liberal-arts/history-of-art/">FIT History
                    of Art
                    Department</a>.
            </p>
            <div class="button-container d-flex">
                <a href="/page/about" class="btn btn-fit-green floating-action mx-auto"
                    aria-label="Learn more about this project">
                    <span class="action-container">
                        Learn More
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true"
                            title="Learn more about this project">
                        </i>
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>