<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/fashion-calendar-data.css', 'FashionCalendarModule'));
$this->headLink()->appendStylesheet('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css', 'screen', null, ['integrity' => 'sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=', 'crossorigin' => '']);
$this->headScript()->appendFile($this->assetUrl('js/fashion-calendar-data.js', 'FashionCalendarModule'));
$this->headScript()->appendFile('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js', 'text/javascript', ['integrity' => 'sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=', 'crossorigin' => '']);
$this->headScript()->appendFile('https://unpkg.com/mirador@3.3.0/dist/mirador.min.js', 'text/javascript');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==', 'crossorigin' => 'anonymous']);
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/corejs-typeahead@1.3.3/dist/typeahead.bundle.min.js', 'text/javascript');
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/chart.js', 'text/javascript');
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="data-header">
    <div class="row justify-content-end">
        <div class="col-12 col-sm">
            <h2>Data</h2>
            <div id="results"></div>
            <ul id="query" class="list-inline"></ul>
        </div>
        <div class="col-12 col-sm-6">
            <form id="data-search">
                <div class="input-group">
                    <input type="search" class="form-control" aria-label="<?php echo $translate('Search'); ?>"
                        autocomplete="off" placeholder="Search by keyword or select names/categories via autocomplete">
                    <button class="btn btn-secondary" type="submit" aria-label="Search">
                        <i class="fas fa-search" title="<?php echo $translate('Search'); ?>" aria-hidden="true"></i>
                    </button>
                </div>
            </form>
            <div class="search-info d-flex justify-content-end mt-2 small">
                <button class="border-0 bg-transparent p-0 link-secondary me-2" data-bs-toggle="modal"
                    data-bs-target="#advanced-search-data">
                    <i class="fas fa-search me-1" aria-hidden="true"></i>
                    <span>Advanced Search</span>
                </button>
                |
                <button class="border-0 bg-transparent p-0 link-secondary ms-2" data-bs-toggle="modal"
                    data-bs-target="#search-tips">
                    <i class="fas fa-info-circle me-1" aria-hidden="true"></i>
                    <span>Search Tips</span>
                </button>
                <!-- Modal -->
                <div class="modal fade" id="advanced-search-data" tabindex="-1"
                    aria-labelledby="advanced-search-data-label" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title fs-5" id="advanced-search-data-label">Advanced Search</h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body placeholder-glow">
                                <span class="placeholder col-7"></span>
                                <span class="placeholder col-4"></span>
                                <span class="placeholder col-4"></span>
                                <span class="placeholder col-6"></span>
                                <span class="placeholder col-8"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="search-tips" tabindex="-1" aria-labelledby="search-tips-label"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h2 class="modal-title fs-5" id="search-tips-label">Search Tips</h2>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body placeholder-glow">
                                <span class="placeholder col-7"></span>
                                <span class="placeholder col-4"></span>
                                <span class="placeholder col-4"></span>
                                <span class="placeholder col-6"></span>
                                <span class="placeholder col-8"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div id="facet" class="col-auto"></div>
        <div id="graph" class="col-auto"></div>
    </div>
</div>
<div id="data-container">
    <div id="loader" class="d-flex justify-content-center align-items-center">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
<div id="modal-container" class="p-0 m-0"></div>
<button id="top-button" type="button" class="btn btn-secondary" title="Go to top">
    <i class="fas fa-long-arrow-alt-up me-1" aria-hidden="true"></i>
    Top
</button>