<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/fashion-calendar-home.css', 'FashionCalendarModule'));
?>
<div id="hero" class="col-12">
    <div class="row align-items-center">
        <div class="col-md-6">
            <img class="img-fluid" src="<?php echo $this->assetUrl('img/finley.png'); ?>"
                alt="Drawing of Ruth Finley on the telephone">
        </div>
        <div class="col-md-6">
            <div id="tag">Over 80 Years of Fashion History</div>
            <p id="lead">
                From 1941 to 2014, Ruth Finley published the <em>Fashion Calendar</em>, an independent, weekly periodical that served as the official scheduling clearinghouse for the American fashion industry. Since 2015, the Council of Fashion Designers of America (CFDA) has managed the official New York Fashion Week (NYFW) schedule. Digitized by the Fashion Institute of Technology, the <em>Fashion Calendar</em> and now the CFDA Fashion Calendar, are both searchable, graphable and mappable.
            </p>
        </div>
    </div>
    <div class="alert alert-danger pb-3 p-md-4 p-lg-5 mt-5 mb-0 bg-white">
        <img id="fcrdcfda" class="d-block mb-3" src="/modules/FashionCalendarModule/asset/img/fashion-calendar-cfda.png" alt="Fashion Calendar x CFDA" />
        <p class="lead">Announcing the <b>Archiving New York Fashion Week: FCRD x CFDA</b> initiative, a collaboration between the Fashion Calendar Research Database and the Council of Fashion Designers of America (CFDA) which brings the NYFW timeline to the present. This ongoing initiative integrates fashion show listings and data from the CFDA Fashion Calendar from 2015 to 2025 into this database. <a href="/page/cfda">Learn more...</a></p>
        <hr>
        <p class="mb-0 lead">
            Help support our next phase, which includes the integration of fashion show images and video from the 1990s to today into the database through our collaboration with <a href="https://www.firstview.com/">FirstVIEW</a>. This includes expanded research capabilities, innovative digital humanities tools, student training programs and research opportunities. <a href="https://impact.fitnyc.edu/fashion-calendar">Donate here</a>...
        </p>
    </div>
</div>
<div id="features" class="col-12">
    <div class="row row-cols-1 row-cols-md-3 gx-lg-5">
        <div class="col feature">
            <h2><span><i class="fas fa-book-open"></i>Browse Issues</span></h2>
            <p>
                Over 39,000 pages from three periodicals published by Ruth Finley have been digitized and made available online for browsing: Fashion Calendar (1941-2014), Home Furnishings Calendar (1947-1951), and Fashion International (1972-2008). For researchers, this method is the closest to handling the material directly. Each issue is directly searchable and can be freely downloaded as a PDF.
            </p>
            <div class="button-container d-flex">
                <a href="/page/issues" class="btn btn-dark floating-action mx-auto" aria-label="Browse Issues">
                    <span class="action-container">
                        Issues
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true" title="Browse Issues">
                        </i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col feature">
            <h2><span><i class="fas fa-table"></i>Explore Data</span></h2>
            <p>
                Information about the events listed in the <em>Fashion Calendar</em> and the CFDA Fashion Calendar—the who, what, when, where—has been extracted and parsed from each issue. Names and entities in the listings (i.e. designers and brands) have been categorized to highlight gender, race, social class, sexual identity, nationality, etc. The data of over 200,000 events can be searched, mapped, and graphed, allowing users to discover rich patterns and threads woven into the history of fashion and the creative industries.
            </p>
            <div class="button-container d-flex">
                <a href="/page/data" class="btn btn-dark floating-action mx-auto" aria-label="Explore Data">
                    <span class="action-container">
                        Data
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true" title="Explore Data">
                        </i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col feature">
            <h2><span><i class="fas fa-info-circle"></i>About</span></h2>
            <p>
                In 2020, FIT was awarded a "Hidden Collections" grant from the Council on Library and Information Resources to digitize the Ruth Finley Collection, which is housed in the FIT Library's Special Collections and College Archives. The project culminated in this site, the Fashion Calendar Research Database, a joint initiative of the <a href="https://www.fitnyc.edu/academics/library/">Gladys Marcus Library</a> and the <a href="https://www.fitnyc.edu/academics/academic-divisions/liberal-arts/history-of-art/">FIT History of Art Department</a>. Be sure to check out our <a href="https://www.instagram.com/fcrd_fit">Instagram</a> for additional content.
            </p>
            <div class="button-container d-flex">
                <a href="/page/about" class="btn btn-dark floating-action mx-auto"
                    aria-label="Learn more about this project">
                    <span class="action-container">
                        Learn More
                        <i class="fas fa-arrow-right me-0 ms-1" aria-hidden="true"
                            title="Learn more about this project">
                        </i>
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>