<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/fashion-calendar-data.css', 'FashionCalendarModule'));
$this->headLink()->appendStylesheet('https://unpkg.com/leaflet@1.9.4/dist/leaflet.css', 'screen', null, ['integrity' => 'sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=', 'crossorigin' => '']);
$this->headLink()->appendStylesheet('https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css', 'screen', null);
$this->headLink()->appendStylesheet('https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css', 'screen', null);
$this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.css', 'screen', null, ['integrity' => 'sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg==', 'crossorigin' => 'anonymous']);
$this->headScript()->appendFile($this->assetUrl('js/fashion-calendar-data.js', 'FashionCalendarModule'));
$this->headScript()->appendFile('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js', 'text/javascript', ['integrity' => 'sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=', 'crossorigin' => '']);
$this->headScript()->appendFile('https://unpkg.com/leaflet.markercluster@1.5.3/dist/leaflet.markercluster-src.js', 'text/javascript');
$this->headScript()->appendFile('https://unpkg.com/leaflet.markercluster.layersupport@2.0.1/dist/leaflet.markercluster.layersupport.js', 'text/javascript');
$this->headScript()->appendFile('https://unpkg.com/mirador@3.3.0/dist/mirador.min.js', 'text/javascript');
$this->headScript()->appendFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==', 'crossorigin' => 'anonymous']);
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/corejs-typeahead@1.3.3/dist/typeahead.bundle.min.js', 'text/javascript');
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/chart.js', 'text/javascript');
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="data-header">
    <div class="row justify-content-end gy-3 gy-md-0">
        <div class="col-12 col-md-7 order-md-last" id="search-container">
        </div>
        <div class="col-12 col-md">
            <h2>Data</h2>
            <div id="results">Fetching data...</div>
            <ul id="query" class="list-inline mb-md-0"></ul>
        </div>
    </div>
    <div class="row mt-md-3 button-row gx-2 gx-sm-3 gx-md-4 gy-3 gy-lg-0">
        <div id="sort" class="col-auto ms-lg-auto order-lg-last"></div>
        <div class="w-100 d-lg-none"></div>
        <div id="facet" class="col-auto"></div>
        <div id="graph" class="col-auto"></div>
        <div id="map" class="col-auto"></div>
        <div id="download" class="col-auto d-none d-md-inline-block"></div>
    </div>
</div>
<div id="data-container">
    <div id="loader" class="d-flex justify-content-center align-items-center">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
</div>
<div id="modal-container" class="p-0 m-0"></div>
<button id="top-button" type="button" class="btn btn-dark" title="Go to top">
    <i class="fas fa-long-arrow-alt-up me-1" aria-hidden="true"></i>
    Top
</button>